# Hibernate settings
#hibernate:
#  dialect: org.hibernate.dialect.PostgreSQLDialect
#  show_sql: true

# Server settings
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081